baseURL = "https://spring-admin.github.io/wangcai-daily/"
languageCode = "zh-CN"
title = "旺财日报"
theme = "PaperMod"

[params]
  description = "由旺仔整理的每日资讯简报"
  author = "旺仔"
  defaultTheme = "auto"
  ShowReadingTime = false
  ShowShareButtons = false
  ShowPostNavLinks = false
  ShowBreadCrumbs = false
  ShowCodeCopyButtons = true
  ShowWordCount = false
  ShowRssButtonInSectionTermList = true
  ShowPageNums = true
  ShowToc = false

[taxonomies]
  tag = "tags"

[outputs]
  home = ["HTML", "RSS"]
  section = ["HTML", "RSS"]

[markup.goldmark.renderer]
  unsafe = true

[languages.zh]
  languageName = "中文"
  weight = 1
